[mgr]
show_hidden = true
linemode = "size"

[opener]
video = [
    { run = 'mpv "$@"', orphan = true, desc = "Play with mpv" },
]

[open]
prepend_rules = [
    { mime = "video/*", use = "video" },
]

[preview]
max_width = 1920
max_height = 1080

[plugin]
prepend_previewers = [
    { mime = "{image,audio,video}/*", run = "mediainfo" },
    { mime = "application/x-subrip", run = "mediainfo" }
]
