[python]
pyenv_version_name = true

[git_metrics]
disabled = true

[git_status]
conflicted = "ğŸ³ "
up_to_date = "âœ“ "
untracked = "ğŸ¤· â€"
stashed = "ğŸ“¦ "
modified = "ğŸ“ "
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘ "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[status]
disabled = false
